### ISSUE TITLE
Update location of hypre repo

### ISSUE THREAD

**Issue by neely4** [LLNL/llnl.github.io#355] opened 2020-06-29 21:51 UTC
I just noticed that the hypre repo linked is their old one here: https://github.com/LLNL/hypre

They have migrated all of their development over to this repo: https://github.com/hypre-space/hypre

We should update accordingly so we don't send people to a repo that looks like it has no work being done on it. Granted - they might figure that out if they catch the repo description, but we shouldn't count on that. Also the new repo has more stars which will bump it up just ahead of SUNDIALS in the rank order! A little competition for more stars might thus ensue!

**Comment by LRWeber** [comment] 2020-06-29 22:42
This would be on the Hypre team to fix.

I assume you are specifically referring to the Radius project Math & Physics list. These lists are generated based on each repo's "topic" tags. (See [`radiuss/README.md`](https://github.com/LLNL/llnl.github.io/blob/bcb50992fd00d151571576a8536fa5c3eb756e44/radiuss/README.md) and [`category/README.md`](https://github.com/LLNL/llnl.github.io/blob/bcb50992fd00d151571576a8536fa5c3eb756e44/category/README.md))

Right now, the `LLNL/hypre` repo topics include the `radiuss` and `math-physics` tags, which mark it for inclusion in that list. Meanwhile, the `hypre-space/hypre` repo has no topic tags at all.
They will need to remove these tags from the `LLNL` repo and add them to the proper `hypre-space` repo.

The `LLNL/hypre` repo will still be included in the "All Software" list and collective data, as it is a part of the LLNL organization.

**Comment by IanLee1521** [comment] 2020-06-29 22:43
@neely4 - Good catch. There's a bit of history really...

The LLNL/hypre repo is archived there, and has some history from before the team moved to their own organization (hypre-space). 

The reason that you don't see the hypre-space/hypre copy on the software.llnl.gov is that it doesn't have the tags that the software.llnl.gov site looks for (and that the LLNL repo DOES have), specifically the: `math-physics`, `library`, `hpc`, `radiuss` tags.

So there are a couple of things we could / should do:

* We should definitely set the tags on the hypre-space/hypre repo (@rfalgout should be able to do this)
* We may possibly also remove them from the llnl/hypre repo to not list that version in the same lists
* It is also possible (@rfalgout and I chatted briefly about this in the past) that we should just delete the llnl/hypre repo and only have the hypre-space/hypre repo. -- Ideally we would have transferred the repo to the new org, but we're too far past that point now.

**Comment by LRWeber** [comment] 2020-06-29 22:51
The good news is it looks like we already set up the [appropriate logo image](https://github.com/LLNL/llnl.github.io/blob/bcb50992fd00d151571576a8536fa5c3eb756e44/assets/images/logos/repo_logos.json#L3) for whenever `hypre-space/hypre` takes its rightful place in the list!

**Comment by rfalgout** [comment] 2020-06-29 23:26
Okay, I've added the same four topics to the hyper-space/hypre repo.  Let me know if I should add any others.  Also, maybe it's a good time to delete the LLNL/hypre repo.  Let me know what you think.  Thanks!

**Comment by IanLee1521** [comment] 2020-06-29 23:48
Thanks @rfalgout .

@neely4 - they should show up when the site re-builds tonight, so check the lists again tomorrow.

**Comment by LRWeber** [comment] 2020-06-30 18:27
I can confirm that the `hypre-space/hypre` repo is now included in the RADIUSS Math & Physics listings!
The `LLNL/hypre` repo is still there as well, but that would be updated once those topic tags are removed or the repo is deleted.

**Comment by rfalgout** [comment] 2020-06-30 19:39
Thanks @LRWeber !  Unless there is an objection from anyone, I'll go ahead and delete the repo.

**Comment by hauten** [comment] 2020-06-30 20:27
Do we need to remove llnl/hypre from _explore/input_lists_subsets.json?

**Comment by IanLee1521** [comment] 2020-06-30 20:28
@rfalgout - Yes, let's just do that, since the official location moved... Not sure if you feel the need to advertise that somehow to your users, but I say let's do it. If you need any help from me let me know.

@hauten - Yes, would you mind doing that?

**Comment by hauten** [comment] 2020-06-30 20:32
> @hauten - Yes, would you mind doing that?
Sure. We have instructions for adding a repo to the site/org but not removing/replacing with new repo. I'll add that too.

**Comment by rfalgout** [comment] 2020-06-30 20:42
Hi @IanLee1521 .  Apparently I will actually need help deleting the repo. :-(  I am not seeing the "Delete this repository" button in the "Danger Zone" (as google tells me I should).  I tried unarchiving first, but that didn't help either.  Thanks!

**Comment by LRWeber** [comment] 2020-06-30 20:45
> Do we need to remove llnl/hypre from _explore/input_lists_subsets.json?

Do we even actually need the subsets anymore?
That input file ultimately generates `explore/github-data/labReposSubsets.json`, however I don't see that data file referenced anywhere.

I believe that may have been our initial solution to listing the RADIUSS repos, which is now superseded by the use of the topic tags.

**Comment by hauten** [comment] 2020-06-30 20:48
I think you're right @LRWeber.

**Comment by IanLee1521** [comment] 2020-06-30 20:50
@LRWeber - I agree. Sounds like the real solution is to remove that whole file :)

@rfalgout - I assume that you concur then on the "delete now, no need to notify further" approach? Might need to be an org owner to do this (which I am, so I can do if you give the 👍 )

**Comment by rfalgout** [comment] 2020-06-30 20:52
@IanLee1521 .  Yes, go ahead and delete LLNL/hypre.  Thanks!

**Comment by LRWeber** [comment] 2020-06-30 20:53
> @LRWeber - I agree. Sounds like the real solution is to remove that whole file :)

I'll work on doing that then. (It'll require editing it out of the scripts and such too.)

**Comment by IanLee1521** [comment] 2020-06-30 20:54
@rfalgout Done!

**Comment by rfalgout** [comment] 2020-06-30 20:56
@IanLee1521  Excellent!  Thanks!

**Comment by LRWeber** [comment] 2020-06-30 21:59
Everything should be in order once the next update runs tonight to clear the deleted repo from our data! 🙂

**Closed by LRWeber** 2020-06-30 21:59 UTC
Labels: radiuss
